title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate in Political Science and Administration by the University of Santiago de Compostela with a master’s degree in Computational Social Science by the University Carlos III de Madrid. With a strong academic background in both fields that brings a unique and comprehensive approach to understanding political systems and societal dynamics.  
  <br><br>
  Capable of applying advanced data analysis techniques and data visualization to uncover patterns and insights within large datasets related to, among others, social behavior. Focused on using these skills and knowledge to drive positive change in the world, particularly with regard to sustainable development and dedicated to develop data-driven strategies and recommendations for tackling political, economic and social issues.
  <br><br>
  <a href="https://www.linkedin.com/in/victoria-costas-salamanca/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
